// Import necessary types and modules
import type { Metadata } from "next"; // Type for metadata in Next.js
import { Geist, Geist_Mono } from "next/font/google"; // Import Google Fonts
import "./globals.css"; // Import global CSS styles

// Configure the Geist Sans font with a CSS variable and subset
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable for the font
  subsets: ["latin"], // Subset for Latin characters
});

// Configure the Geist Mono font with a CSS variable and subset
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable for the font
  subsets: ["latin"], // Subset for Latin characters
});

// Define metadata for the application
export const metadata: Metadata = {
  title: "Create Next App", // Title of the application
  description: "Generated by create next app", // Description of the application
};

// Root layout component for the application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // Children components to be rendered inside the layout
}>) {
  return (
    <html
      lang="en" // Set the language of the document to English
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} // Apply font variables and styles
    >
      <body className="min-h-full flex flex-col">
        {/* Render the children components */}
        {children}
      </body>
    </html>
  );
}